#
# types: lifetime-statistic, level-statistic, achievement, economy,
#
#
#
#

levels:
  1:
    requirements:
      # money
      - type: economy
        title: $100
        money: 100

      # advancement
      - type: advancement
        title: Complete the Stone Age Advancement
        advancement: story/mine_stone

      # lifetime statistic
      - type: lifetime-statistic
        title: Mine a total of 128 stone
        metric: MINE_BLOCK
        target: stone
        value: 128

      # level statistic
      - type: level-statistic
        title: Mine 64 stone
        metric: MINE_BLOCK
        target: stone
        value: 64

#    rewards:
#      commands:
#        - "/give USER item:cookie"
